version: '3.8'

services:
  app:
    build: .
    #ports:
    #  - "8000:8080"  
    #  - "8443:443"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=mydatabase;Port=5432;Username=myuser;Password=mypassword;Include Error Detail=true
      # ASP.NET Core lauscht standardmäßig auf 8000 im Container
      - ASPNETCORE_URLS=http://+:8000
      - ConverterSettings__Url=http://converter:8080
    volumes:
      - ./uploads:/app/wwwroot/uploads
    depends_on:
      postgres:
        condition: service_healthy  # Warte auf healthy DB
    networks:
      - app-network
    restart: always

  converter:
    build:
      context: .
      dockerfile: ZUMI_Converter/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./uploads:/app/wwwroot/uploads
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:  # Check, ob DB ready
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # WICHTIG: Hier binden wir das bestehende Zertifikat vom HOST ein
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Für zukünftige Erneuerungen (Webroot Challenge)
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"  # Nur HTTP – öffentlich auf 80 (kein 443)
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    restart: always
      
  # NEU: Der Certbot Container
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      # Auch Certbot muss Zugriff auf den echten Ordner haben, um zu erneuern
      - /etc/letsencrypt:/etc/letsencrypt
    # Dieser Befehl prüft alle 12h, ob ein Zertifikat erneuert werden muss
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge