### POST Login to get JWT Token
POST http://localhost/api/v1/auth/token/
Content-Type: application/json

{
  "Email": "test@testerei.org",
  "Password": "test"
}

> {%
    client.global.set("auth_token", response.body.access);
    client.log("JWT Token gespeichert: " + client.global.get("auth_token"));
%}
