<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="out\web.config" />
      <_ContentIncludedByDefault Remove="out\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="out\appsettings.json" />
      <_ContentIncludedByDefault Remove="out\ZUMI_Backend.deps.json" />
      <_ContentIncludedByDefault Remove="out\ZUMI_Backend.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="out\ZUMI_Backend.staticwebassets.endpoints.json" />
    </ItemGroup>

</Project>
